// Turns assets/src originals into AVIF/WebP/JPEG at responsive widths in public/img,
// writes src/generated/images.ts, and builds public/og.jpg.
import sharp from 'sharp';
import { mkdir, writeFile, access } from 'node:fs/promises';

const exists = async (p) => access(p).then(() => true, () => false);

// key -> source, widths, optional blur (for "video coming soon" posters that must not be readable)
const jobs = {
  hero:         { src: 'assets/src/hero.jpeg',          widths: [480, 640, 800, 1280] },
  casual:       { src: 'assets/src/casual.jpeg',        widths: [480, 960] },
  wall:         { src: 'assets/src/wall.png',           widths: [720, 1200, 1686] },
  bengaluruRun: { src: 'assets/src/bengaluru-run.png',  widths: [640, 1080, 1440] },
  desilingo:    { src: 'assets/src/desilingo-card.png', widths: [640, 1080, 1440] },
  mangalore:    { src: 'assets/src/mangalore.jpeg',     widths: [480, 960] },
  beach:        { src: 'assets/src/beach.png',          widths: [480, 960, 1500] },
  waterfall:    { src: 'assets/src/waterfall.png',      widths: [640, 1280] },
  cafe:         { src: 'assets/src/cafe.png',           widths: [480, 960] },
  lighthouse:   { src: 'assets/src/lighthouse.png',     widths: [480, 960] },
  posterInvoice:   { src: 'assets/src/poster-invoice.png',   widths: [640, 1280], frame: 'assets/src/frame-invoice.jpg',   blur: 28 },
};

await mkdir('public/img', { recursive: true });
await mkdir('src/generated', { recursive: true });
const out = {};

for (const [key, job] of Object.entries(jobs)) {
  // If prep-video.mjs has extracted a frame, use it sharp; otherwise blur the Screen Studio thumbnail.
  let src = job.src, blur = job.blur ?? 0, pending = false;
  if (job.frame) {
    if (await exists(job.frame)) { src = job.frame; blur = 0; }
    else pending = true;
  }
  let base = sharp(src).rotate();
  const meta = await base.metadata();
  out[key] = { width: meta.width, height: meta.height, avif: [], webp: [], jpg: '', pending };
  for (const w of job.widths) {
    let r = base.clone().resize({ width: w, withoutEnlargement: true });
    if (blur) r = r.blur(blur * (w / 1280));
    await r.clone().avif({ quality: 55, effort: 5 }).toFile(`public/img/${key}-${w}.avif`);
    await r.clone().webp({ quality: 80 }).toFile(`public/img/${key}-${w}.webp`);
    out[key].avif.push(w); out[key].webp.push(w);
  }
  let j = base.clone().resize({ width: job.widths.at(-1), withoutEnlargement: true });
  if (blur) j = j.blur(blur);
  await j.jpeg({ quality: 82, mozjpeg: true }).toFile(`public/img/${key}.jpg`);
  out[key].jpg = `/img/${key}.jpg`;
  console.log(`${key.padEnd(16)} ${meta.width}x${meta.height}  widths ${job.widths.join('/')}${blur ? '  (blurred placeholder)' : ''}`);
}

// Open Graph card (old design; public/og.jpg is now rendered from og.html, so this only runs with OG=1).
if (process.env.OG) {
  const W = 1200, H = 630;
  const portrait = await sharp('assets/src/hero.jpeg').rotate().resize({ width: 430, height: 538, fit: 'cover', position: 'top' }).toBuffer();
  const svg = `<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">
    <rect width="${W}" height="${H}" fill="#F7F3EC"/>
    <rect x="700" y="70" width="40" height="40" rx="3" transform="rotate(-8 720 90)" fill="#FFD84D"/>
    <rect x="1030" y="520" width="44" height="44" rx="3" transform="rotate(10 1052 542)" fill="#FFB3C1"/>
    <rect x="640" y="540" width="36" height="36" rx="3" transform="rotate(14 658 558)" fill="#A8D8FF"/>
    <text x="80" y="230" font-family="Georgia, 'Times New Roman', serif" font-size="84" font-weight="700" fill="#14120F">Sagar</text>
    <text x="80" y="320" font-family="Georgia, 'Times New Roman', serif" font-size="84" font-weight="700" fill="#14120F">Kotian</text>
    <text x="82" y="390" font-family="Helvetica, Arial, sans-serif" font-size="26" fill="#5C574E">First non-eng hire. I bring in the demand,</text>
    <text x="82" y="428" font-family="Helvetica, Arial, sans-serif" font-size="26" fill="#5C574E">keep the customers, and grade the AI's homework.</text>
    <text x="82" y="500" font-family="Helvetica, Arial, sans-serif" font-size="20" font-weight="700" fill="#2E7D4F">Founder's Office · GTM &amp; Customer Success · Bengaluru</text>
  </svg>`;
  await sharp(Buffer.from(svg))
    .composite([{ input: await sharp(portrait).composite([{ input: Buffer.from(`<svg width="430" height="538"><rect width="430" height="538" rx="18" fill="#000"/></svg>`), blend: 'dest-in' }]).png().toBuffer(), left: 700, top: 46 }])
    .jpeg({ quality: 86, mozjpeg: true }).toFile('public/og.jpg');
  console.log('og.jpg 1200x630');
}

await writeFile('src/generated/images.ts',
  `// Generated by scripts/prep-images.mjs. Do not edit.\nexport const images = ${JSON.stringify(out, null, 2)} as const;\nexport type ImageKey = keyof typeof images;\n`);
console.log('wrote src/generated/images.ts');
